#!/bin/sh

# i3status configuration file.
# see "man i3status" for documentation.


# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
   output_format = "i3bar"
   colors = true
   markup = pango
   color_good = "#6cff54"  # Green
   color_degraded = "#ffe24f"  # Gold
   color_bad = "#ff4b4b"  # Red
   separator = "="

   # color_good = "#b3c059"
   # color_degraded = "#f3c15e"
   # color_bad = "#f56f6f"
}

# order += "battery all"

order += "ethernet _first_"
order += "disk /"
order += "cpu_temperature 0"
order += "gpu_temperature 0"
order += "wireless _first_"
order += "load"
order += "memory"
order += "volume master"
order += "tztime local"

wireless _first_ {
       # format_up = "W: (%quality at %essid) %ip"
       format_up = "W: (%quality) Leaked IP: %ip"
       format_down = "W: down"
}

ethernet _first_ {
   format_up = "🌐 %ip (%speed)"
   format_down = "⚠️ no ethernet"
}

# battery all {
#   format = "%status %percentage %remaining"
# }

disk "/" {
   # format = "%avail"
   format = "%avail"
   # format = "<span color='#f3c15e'>%avail</span>"
}

cpu_temperature 0 {
   format = "%degrees °C"
   max_threshold = 69
   format_above_threshold = "  %degrees °C"
   path = "/sys/class/thermal/thermal_zone0/temp"
}

# gpu_temperature 0 {
#   status_command ~/.config/i3status/gpu-temp.sh
# }

load {
   format = "Hot Loads: %1min"
   max_threshold = 8
}

memory {
   memory_used_method = "memavailable"
   threshold_degraded = "25%"
   threshold_critical = "10%"
   format = "%used"
   format_degraded = "%used"
   # prefix_type = "decimal"
}

volume master {
   # format_muted = " muted (%volume)"
   # format = "%volume"
   format = "  %volume"
   format_muted = "<span color='#ff4b4b'> muted %volume</span>"
   # format = "<span color='#9ec9e3'>♪ %volume</span>"
   # format_muted = "<span color='#f56f6f'>♪ muted (%volume)</span>"
   device = "pulse"
   mixer = "Master"
   mixer_idx = 0
}

tztime local {
   locale = "en_US.UTF-8"
   format = "<span color='#b6abe3'>  %a %d-%m-%Y</span> <span color='#b6abe3'>%H:%M:%S</span>"
   # format = " <span color='#b6abe3'>  %a %d/%m</span> <span color='#b6abe3'>%H:%M:%S</span>"
   # format = "  %a %-d %b %H:%M:%S"
}
