"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = "$all"

[character]
success_symbol = "[➜ ](green)"
error_symbol = "[✘ ](red)"

[directory]
format = '󰍲  [$path]($style)[$read_only]($read_only_style) '
read_only = " 󰌾"
truncation_length = 4
truncation_symbol = '~/'
style = "bold bright-cyan"

[c]
symbol = " "
style = "bold bright-purple"
format = 'via [$symbol($version(-$name) )]($style)'

[cpp]
symbol = " "
style = "bold bright-purple"
format = 'via [$symbol($version(-$name) )]($style)'
disabled = false

[cmake]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
deleted = '✘ '
behind = '⇣ '
staged = '[++\($count\)](green)'
style = "bold bright-purple"

[fossil_branch]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[nodejs]
symbol = " "

[rust]
symbol = " "

[sudo]
symbol = '👩‍💻 '
style = 'bold bright-blue'
disabled = false

[gradle]
symbol = " "

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[cmd_duration]
style = "bold bright-yellow"

#[custom.stunnel]
#when = "ps aux | grep stunnel | grep -v grep"
#command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
#style = "red"
#format = "[TUNNEL OPEN for $output]($style)"
